{% set xorg_name = "xbitmaps" %}
{% set xorg_category = "data" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.1.3" %}
{% set sha256 = "ad6cad54887832a17d86c2ccfc5e52a1dfab090f8307b152c78b0e1529cd0f7a" %}
{% set am_version = "1.16" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - m2-autoconf                  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool                   # [win]
    - pkg-config                   # [unix]
    - m2-pkg-config                # [win]
    - m2-base                      # [win]
    - make                         # [unix]
    - m2-make                      # [win]
    - gnuconfig  # [unix]
    - {{ compiler("c") }}          # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
  host:
    - xorg-util-macros

test:
  commands:
    - test -e $PREFIX/include/X11/bitmaps/gray  # [not win]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Bitmaps shared between X applications'

extra:
  recipe-maintainers:
    - epruesse
    - pkgw
