appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ova19eRqs0/iQuspPGbObQvDJYeKWqdz3qVoeYLY6nlBOhvGtxFYSlj27K+VLGW023dvVCVtfBjDgTJazfBf8dUqI4xLL4a5Gnrh8Q1SsQZo9l2NGcXH/srgzv4iyrNlwwdwLimzl443am/Tr9AjjmSxgI+6qCE6kcKJ4FrB8Nx1vCn2X70SdoS50DDA5ZJAFjcCxhX1a7M3kQgCZzEHf+COHH5l03LBgPeOfkm+FvzogBSR37uHQtvQGXhKYwDavP55cpMdsmeWZIE+KhyjoqdXdzeXSzZWRhzfHo3XMhjSTk0SKoUM8/uKbQ4Iy9M4HM/ACv1sLO047hjMP8xfJsjgJDJg6gRE+6hlsk/P38S3Vjb+fdOvFNDJNe1o7hrqIeC9VnSBo4JU0ISqNomzaoSIS3FJnITk0KG/dJWcljFPl+ZrkBJIOw89fUnl/J1pfqXYmLILsqu2ot90iyPiYplOoMeNltQf+Q1BISGJWpBGGs4egOuLp5t1B/+1mh08CF8ULpUy33PwgMfJRy/SpH/FZh3QW7u/ZTPr/L3UHc2lS+6LyiYN75Z5m1uCfMnfdetCnOO+xpMaHG04+tRgQrvX38kk+Em3GP4Idx1m6Nzxc4vW/aAL0h6VJyooAsY807WeVI+88+Rz2TxyygnZ4HBiko323tfVReUHZHeJtw4=}
conda_forge_output_validation: true
