travis:
  secure:
    BINSTAR_TOKEN: HEvEealZ5jIqdvl/OPC57jnaN/Euk8GYPvhmP0DyjSVhP0/IzqgAmqd+92OwT5c++OZZd6W/9emUrp/WmHl4Srs0ibABTMmtklUog1neUnvJEMd2dwQ7QhVcQmdbXBKCSS5O/63tJQewxV9kCDAh9OkMoi0AnkIbysFFBL6L1/HSbrfat/ywn0P38RNcjhEYgAbUyIDI+9GGgi/t5b1rWbenpbRnyF7vP8obMIms/hMKMt8t4lWkxlOCFmA4q040JGpRwBBA8KWBNSZQqcDjtnKTeD9XIItVAefG9sSHu4EzORFiaFlCHti45ObUbXZnWkDfDYPtoofbIbSPpETXLwmrKT3wtWcn8Hjrp5xMtAqXk6AXtomEcuoanWZbp90ELKtf+Y8P+Gsr7gUsXqUpgEK7grHHESQhoY/XpyiHp7jphNsmfZuwcmKJGzPT2hTZSXIFOebEPCRaBYVYE3KcJFuBGmrcmIgxAKB9xf+SSokKdZr3MUGCwYfmjlCEyafHJqhDIba+0f6ETqmSBa6sEwbtYp+KkuanBFfaHI/MeYyhV9Q3Xcg2EPVbPutOEvx3yrqGh9rUUVappbVMjFonFfefBiEHmBCMPb8V5Z+M3IT5CEmPf3znDZoxqVl8N1jPUmzISVSbakQQTV8QtRALRK60Nppsw04HkzDCCIjTMrQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
